-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0xDNtabXgIzqZwE1
k+wfA5gn+U4EECJFqUQoN0lbdM+gCgYIKoZIzj0DAQehRANCAAT+9ytVoaOIKq5I
rK0O/As2JbKxZviN6yFEvGgiPbE67tdNb/Prlsbi1l7UJcuA2TNRLN5F3plUjxO7
0v5I/Nkc
-----END PRIVATE KEY-----